import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  BellOutline,
  BellFill,
  NotificationOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  DeleteOutline,
  EyeOutline,
  EyeInvisibleOutline,
  MessageOutline,
  HomeOutline,
  DollarOutline,
  AuditOutline,
  AppstoreOutline,
  ClockCircleOutline,
  PlusOutline,
  FileTextOutline,
  WalletOutline,
  ArrowUpOutline,
  ArrowDownOutline,
  ShopOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline, 
  MenuUnfoldOutline, 
  DashboardOutline, 
  FormOutline,
  BellOutline,
  BellFill,
  NotificationOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  DeleteOutline,
  EyeOutline,
  EyeInvisibleOutline,
  MessageOutline,
  HomeOutline,
  DollarOutline,
  AuditOutline,
  AppstoreOutline,
  ClockCircleOutline,
  PlusOutline,
  FileTextOutline,
  WalletOutline,
  ArrowUpOutline,
  ArrowDownOutline,
  ShopOutline
];

